# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import imsrc
from PyQt5 import*
from PyQt5.QtWidgets import *
from PyQt5.QtGui import*
import sys
import glob
import serial

class user:
    def __init__(self, id, sex=None, age=None, height=None, weight=None, location=None, emotional=None, frequency=None, video_data=None):
        self.id = id
        self.sex = sex #M:male F:female
        self.age = age
        self.location = location
        self.height = height
        self.weight = weight
        self.emotional = emotional #Y: emotional N: not emotional
        self.frequency = frequency #0: never 1: every year 2: every 6 months 3: every month 4: every week 5: every 1-3 days
        self.video_data = video_data
        self.videos = []

    def to_file(self, filepath):
        with open(filepath, 'a') as f:
            f.write(str(self.id) + ',' + str(self.sex) + ',' + str(self.age) + ',' + str(self.height) + ',' + str(self.weight) + ',' + str(self.location) + ',' + str(self.emotional) + ',' + str(self.frequency) + ',' + str(self.video_data) + '\n')
            f.close()

class video:
    def __init__(self, id=None, emotion_dev=None, emotion_test=None, device_data=None):
        self.id = id 
        self.emotion_dev = emotion_dev
        self.emotion_test = emotion_test
        self.device_data = device_data
    
    def to_file(self, filepath):
        with open(filepath, 'a') as f:
            f.write(str(self.id) + ',' + str(self.emotion_dev) + ',' + str(self.emotion_test) + ',' + str(self.device_data) +'\n')
            f.close()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 231, 91))
        self.label.setStyleSheet("image: url(:/logo/imgsrc/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 80, 151, 41))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 231, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButtonGroup = QButtonGroup()
        self.radioButtonGroup.setExclusive(False)  
        self.radioButton_Male = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Male.setGeometry(QtCore.QRect(80, 10, 63, 17))
        self.radioButton_Male.setObjectName("radioButton_Male")
        self.radioButtonGroup.addButton(self.radioButton_Male)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 62, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radioButton_Female = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Female.setGeometry(QtCore.QRect(150, 10, 62, 17))
        self.radioButton_Female.setObjectName("radioButton_Female")
        self.radioButtonGroup.addButton(self.radioButton_Female)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 200, 231, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 62, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.spinBox_Age = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_Age.setGeometry(QtCore.QRect(70, 10, 61, 20))
        self.spinBox_Age.setMinimum(6)
        self.spinBox_Age.setObjectName("spinBox_Age")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 240, 231, 41))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_Emotional = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Emotional.setGeometry(QtCore.QRect(160, 10, 70, 21))
        self.checkBox_Emotional.setText("")
        self.checkBox_Emotional.setObjectName("checkBox_Emotional")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 280, 231, 71))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalSlider_MovieFreq = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_MovieFreq.setGeometry(QtCore.QRect(40, 40, 160, 22))
        self.horizontalSlider_MovieFreq.setMaximum(5)
        self.horizontalSlider_MovieFreq.setPageStep(1)
        self.horizontalSlider_MovieFreq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_MovieFreq.setObjectName("horizontalSlider_MovieFreq")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 360, 91, 61))
        self.pushButton.setObjectName("pushButton")
        self.button_counter = 0
        self.pushButton_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Reset.setGeometry(QtCore.QRect(80, 440, 91, 61))
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "     NEUROTECH"))
        self.label_3.setText(_translate("MainWindow", "Personal Informations"))
        self.radioButton_Male.setText(_translate("MainWindow", "Male"))
        self.label_4.setText(_translate("MainWindow", "Gender :"))
        self.radioButton_Female.setText(_translate("MainWindow", "Female"))
        self.label_5.setText(_translate("MainWindow", "Age :"))
        self.label_6.setText(_translate("MainWindow", "Are you emotional ?"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>How often do you watch movies?</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Start Video"))
        self.pushButton.clicked.connect(self.clickme)
        self.pushButton_Reset.clicked.connect(self.reset)
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
    def clickme(self):
        self.button_counter = self.button_counter + 1
    def reset(self):
        self.radioButton_Female.setChecked(False)
        self.radioButton_Male.setChecked(False)
        self.checkBox_Emotional.setChecked(False)
        self.horizontalSlider_MovieFreq.setValue(0)
        self.spinBox_Age.setValue(6)

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        EXIT_CODE_REBOOT = -123
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)
        timer = QtCore.QTimer(self)
        timer.timeout.connect(self.data)
        timer.start(100) #Veri akış gecikmesi.
        self.data() # Veri tazeleme fonksiyonu.
    def data(self):
        if self.radioButton_Male.isChecked():
            user_data.sex = 'M'
        if self.radioButton_Female.isChecked():
            user_data.sex = 'F'
        user_data.age = self.spinBox_Age.value()
        if self.checkBox_Emotional.isChecked():
            user_data.emotional = 'Y'
        else:
            user_data.emotional = 'N'
        user_data.frequency = self.horizontalSlider_MovieFreq.value()
        if self.button_counter%2 != 0:
            self.pushButton.setText("Stop Video")
        else:
            self.pushButton.setText("Start Video")


if __name__ == "__main__":
    #fd = open('data/user_count', 'r')
    #id = int(fd.readline())
    #fd.close()
    user_data = user(id)

    print("Baslatiliyor...")
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow() # Ana pencere oluşturulur.
    window.show() #Oluşturulan pencere ekranda gösterilir.
    sys.exit(app.exec_())